# Generated by Django 3.1.7 on 2021-03-25 17:23

from django.db import migrations, models
from django.db.migrations.operations.fields import AlterField
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fila',
            old_name='db',
            new_name='area',
        ),
        migrations.AlterField(
            model_name='dato',
            name='dato',
            field=models.BinaryField(blank=True, editable=True, max_length=65536, null=True, verbose_name='Valor'),
        ),
    ]
