# Generated by Django 3.1.7 on 2021-03-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='filas',
            field=models.ManyToManyField(related_name='datos', to='app.Fila'),
        ),
    ]
