# Generated by Django 3.1.7 on 2021-03-27 22:42

import app.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dato_filas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatoProcesado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('mod_at', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('dato', app.fields.MultiTypeField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_procesados', to='app.area')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_procesados', to='app.fila')),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
