# Generated by Django 3.1.7 on 2021-03-30 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210327_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datoprocesado',
            options={'ordering': ['date']},
        ),
    ]
