# Generated by Django 3.1.7 on 2021-03-30 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210330_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoprocesado',
            name='raw_dato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_procesados', to='app.dato'),
        ),
    ]
